language: python
python:
    - "2.7"

install:
    - pip install unittest2
    - travis/drafter_installation.sh
    - travis/wkhtmltopdf_installation.sh
    - sudo python setup.py install

script: 
    - python fabre_test.py
    - fabre -i apib-example/fiware-ngsi-v2.apib -o ~/out/test.pdf --pdf

branches:
  only:
    - master
    - develop